services:
  postgres:
    image: postgres:17
    container_name: postgres_ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - ecommerce_net
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  ecommerce_data:
  grafana_data:

networks:
  ecommerce_net:
